import os
from dataclasses import dataclass, field

import tomlkit

CONFIG_FILE = "config.toml"

DEFAULT_CONFIG_TOML = """# R.O.V.E.R Configuration File
# This file is automatically generated. You can edit it manually or via the Web UI.

[scanner]
# The maximum time in seconds to wait for a scan to complete (placeholder)
timeout_seconds = 600

[ui]
# The default tab to open when viewing the dashboard (placeholder)
default_tab = "repo"
"""


@dataclass
class ScannerConfig:
    timeout_seconds: int = 600


@dataclass
class UIConfig:
    default_tab: str = "repo"


@dataclass
class RoverConfig:
    scanner: ScannerConfig = field(default_factory=ScannerConfig)
    ui: UIConfig = field(default_factory=UIConfig)


def load_config() -> RoverConfig:
    """Load configuration from config.toml, creating it with defaults if missing."""
    if not os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, "w") as f:
            f.write(DEFAULT_CONFIG_TOML)
        return RoverConfig()

    with open(CONFIG_FILE, "r") as f:
        doc = tomlkit.loads(f.read())

    scanner_data = doc.get("scanner", {})
    ui_data = doc.get("ui", {})

    scanner_config = ScannerConfig(
        timeout_seconds=scanner_data.get("timeout_seconds", 600)
    )
    ui_config = UIConfig(default_tab=ui_data.get("default_tab", "repo"))

    return RoverConfig(scanner=scanner_config, ui=ui_config)


def save_raw_config(raw_toml: str) -> None:
    """Validate and save raw TOML string to config.toml, preserving user comments."""
    # This acts as validation - it will raise tomlkit.exceptions.ParseError if invalid
    tomlkit.loads(raw_toml)
    with open(CONFIG_FILE, "w") as f:
        f.write(raw_toml)


def read_raw_config() -> str:
    """Read the raw TOML string from config.toml for editing in the UI."""
    if not os.path.exists(CONFIG_FILE):
        return DEFAULT_CONFIG_TOML
    with open(CONFIG_FILE, "r") as f:
        return f.read()


# Global settings instance
settings = load_config()
